baseURL = "https://apap.netlify.com/"
languageCode = "fr-fr"
languageLang = "fr"
defaultContentLanguage = "fr"
title = "Joyeux Anniversaire Apap'"
theme = "apap"
googleAnalytics = ""
disableLiveReload = false
disableKinds = ["RSS","taxonomy", "taxonomyTerm"]
relativeURLs = true
staticDir = "static"

[languages]
  [languages.fr]
    languageName = "Français"
    languageCode = "fr-fr"
    languageLang = "fr"
    weight = 1
    contentDir = "content"

[params]
  description = "Apap' est un être drôlement sympathique qui mérite bien quelques vidéos."
  homeTitle = " - Le meilleur des kakapos"
  linkedin = ""
  og_image = "images/visuel-partage.jpg"
  mail = "contact@double.cat"
  footer = "Fait par les chats."

[markup.goldmark.renderer] 
unsafe= true

[server]

  [[server.headers]]
    for = "/**.html"
    [server.headers.values]
      Content-Security-Policy = "script-src localhost:1313"
      Referrer-Policy = "strict-origin-when-cross-origin"
      X-Content-Type-Options = "nosniff"
      X-Frame-Options = "DENY"
      X-XSS-Protection = "1; mode=block"